### ISSUE TITLE
Alexa announce make one echo show play music randomly

### ISSUE THREAD

**Issue by PaulBiod** [energywave/multinotify#5]
Hi,
Since I use multinotify,  an announcement make one of my alexa play music (the last radio I listened to)

I use it like this : 

in the automation : 

service: script.multinotify
data:
  message: Début nébulisation
  alexa_target: media_player.partout (is a group of 3 echos)
  alexa_type: announce
  
  In the logs, I have this : 
  
Last multinotify Alexa announcment changé en Début nébulisation.
13:00:07 - Il y a 10 minutes
Media players - Event - Backup volume_level déclenché par l'événement 'state_changed'
13:00:05 - Il y a 10 minutes
Media players - Event - Backup volume_level déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:04 - Il y a 10 minutes
Media players - Event - Backup volume_level déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:01 - Il y a 10 minutes
Media players - Event - Backup volume_level déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:01 - Il y a 10 minutes
Management of Alexa/TTS devices BEFORE the announcment éteint déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:01 - Il y a 10 minutes
Media players - Event - Backup volume_level déclenché par l'événement 'state_changed'
13:00:01 - Il y a 11 minutes
Management of Alexa/TTS devices BEFORE the announcment activé déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:00 - Il y a 11 minutes
Management of Alexa/TTS devices BEFORE the announcment started déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:00 - Il y a 11 minutes - Historique des exécutions
Management of Alexa/TTS devices BEFORE the announcment éteint déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:00 - Il y a 11 minutes
Media players - Event - Backup volume_level déclenché par l'événement 'state_changed'
13:00:00 - Il y a 11 minutes
Management of Alexa/TTS devices BEFORE the announcment activé déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:00 - Il y a 11 minutes
Management of Alexa/TTS devices BEFORE the announcment started déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:00 - Il y a 11 minutes - Historique des exécutions
Management of Alexa/TTS devices BEFORE the announcment éteint déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:00 - Il y a 11 minutes
Media players - Event - Backup volume_level déclenché par l'événement 'state_changed'
13:00:00 - Il y a 11 minutes
Management of Alexa/TTS devices BEFORE the announcment activé déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:00 - Il y a 11 minutes
Management of Alexa/TTS devices BEFORE the announcment started déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:00 - Il y a 11 minutes - Historique des exécutions
Ensure DND initialization for multinotify éteint déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:00 - Il y a 11 minutes
Ensure DND initialization for multinotify activé déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:00 - Il y a 11 minutes
Ensure DND initialization for multinotify started déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:00 - Il y a 11 minutes - Historique des exécutions
Multinotify - Smart, rich and powerful notifications activé déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:00 - Il y a 11 minutes
Multinotify - Smart, rich and powerful notifications started déclenché par l'automatisation balcon nebulisation déclenché par l'heure pattern
13:00:00 - Il y a 11 minutes - Historique des exécutions

The last activity of the echo which has the problem, is tunein radio. But it's not playing while it makes an annoucement, so, it should not restore tunein

EDIT: for what it's worth, the problem happens only on echo show 5 with fire os 6.5.5.9 (and there is no update), while others echo show running 6.5.6.0 have no problem.

EDIT 2: it seems that this bhavior has to see with the restore music functionality, cause when I do a simple annoucement like this, I have no problem : 

service: notify.alexa_media
data:
  message: test
  target: media_player.evrywhere
  data:
    type: announce

EDIT 3: 
I tried with spotify (I played spotify on it, then stopped it.) 
Then I use the card you provide to send a message to a specific echo show, and sent a message to it, and after the message, the echo played spotify.

EDIT 4 and FINAL edit: 
Problem is with alexa media integration, even when player is stopped, it keeps in "playing" state. After reloading Alexa media player integration, it works.
So sorry for this

Thanks

**Comment by energywave** [comment]
Bonjour Paul, I'll reply in english for the benefit of other (and because I've studied french so much years ago 😄 )
Unfortunately it seems a weird bug with Alexa Media Player integration. I've already seen and participated in previous issues about that but the issue is still there.
It seems that the websocket that the integration has with Amazon server at a random point is stopping to work, so it stops to receive events update from the server and the status of all echo devices is freezed in what it was in that moment.
The last issue (where I just commented) is [this](https://github.com/custom-components/alexa_media_player/issues/1953) but the author seems not anymore interested in supporting his integration and is a little rough in asnwers.

Clearly multinotify is backing up previous status to restore it later, after the announce. But if the previous status is out of synch with reality it will act in a weird way (like you was experiencing) and I cannot do anything about that, unluckily.

In reality I've already put a workaround to mitigate volume issue when the websocket stops working: every time I set the volume before and after the announcement I force an update of the volume attribute of all the involved echo devices with the volume I've set. That's because even the volume is a data that is received exclusively through the websocket and never updated when you change it using a service in Home Assistant (I think this is an easy to resolve issue in the integration but the author was rough on that and told me "you can do it by yourself by changing my code but then you'll have to support all the issues that will arise from that as I don't want to bother myself" or something similar...).
This means that without my workaround the volume of echo will forever be not in sync with what I've set. This is not covering the case where you change the volume with physical buttons or by voice, but that can only work if the websocket works as it should.
But at least when I set the volume the attribute is updating accordingly to the benefit of what is going on next and the next backup/restore of volume...

If you want to put your comment in the above issue... ;)

**Comment by PaulBiod** [comment]
Hi Energywave,

thanks for the explanation. Definitively, it's so sad that some alexa media player bugs have a big impact on other integrations, like yours, and for sure, alexa media player is used by so many users, I can't understand why, if the author is not interested anymore, there isn't someone  willing to maintain it.
By the way, i noticed last version is from june 29th, so there is some kind of updates.
I create an automation to reload the integration every night, but it's just to limit the bugs, not even a workaround.
Thanks for your good work on multinotify, I definitively love it. If you plan to make it even better, I have some ideas,. The DND mode is really good with the force option, maybe an "alternative media player" option would be nice with the "force" option.
Anyway, thanks very much, hope that alexa media player bugs will be fixed so that we can enjoy and use your integration as it deserves.

**Comment by energywave** [comment]
Thank you for your kind words! I didn't understand your idea about DND. Please explain it better so that I can evaluate as I hope to find time to write some improvements that I have in my mind, I evaluate everything.

**Comment by PaulBiod** [comment]
Sure, let me explain : The DND mode prevent from receiving anything, but we could reroute the TTS or announcements to another device. This way, we could announce on every device during day, and only to a specific device (if param "force" is set to false) during night. So that our wifes can sleep and we, guys, still receive the messages on our desk device :)

**Comment by PaulBiod** [comment]
Hi, another suggestion : actually, tts is used with an established language (IT). I changed it on the file, but it would be usefull to be able to change the language directly via a variable on the form of an automation. I know it's possible cause when I use TTS google_translate, I can specify a language.  Maybe not usefull for everyone, but in many cases, different languages can be spoken in a house (I speak french, my wife spanish) :)
